<a href="https://colab.research.google.com/github/sphynxlee/NSCCAI2/blob/main/math_algs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy as sp


In [3]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
A.dtype

dtype('int64')

In [5]:
A.shape

(3, 2)

In [6]:
A.T.shape

(2, 3)

In [8]:
rs = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [9]:
rs.reshape(3,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [10]:
rs.reshape(12,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [13]:
rando = np.random.rand(4,6)
short_rando = np.round(rando, decimals=2)
short_rando

array([[0.34, 0.8 , 0.73, 0.65, 0.03, 0.63],
       [0.66, 0.48, 0.47, 0.65, 0.52, 0.4 ],
       [0.22, 0.09, 0.89, 0.37, 0.52, 0.98],
       [0.39, 0.86, 0.84, 0.17, 0.57, 0.19]])