<a href="https://colab.research.google.com/github/sphynxlee/NSCCAI2/blob/main/math_algs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import scipy as sp


In [3]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
A.dtype

dtype('int64')

In [5]:
A.shape

(3, 2)

In [6]:
A.T.shape

(2, 3)

In [8]:
rs = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])

In [9]:
rs.reshape(3,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])

In [10]:
rs.reshape(12,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [13]:
rando = np.random.rand(4,6)
short_rando = np.round(rando, decimals=2)
short_rando

array([[0.34, 0.8 , 0.73, 0.65, 0.03, 0.63],
       [0.66, 0.48, 0.47, 0.65, 0.52, 0.4 ],
       [0.22, 0.09, 0.89, 0.37, 0.52, 0.98],
       [0.39, 0.86, 0.84, 0.17, 0.57, 0.19]])

In [15]:
A = 5*np.ones((3,3))
A

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [18]:
B = 3*np.ones((3,3))
B

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [21]:
# element wise
C = A * B
C

array([[15., 15., 15.],
       [15., 15., 15.],
       [15., 15., 15.]])

In [23]:
C1 = A @ B
C1

array([[45., 45., 45.],
       [45., 45., 45.],
       [45., 45., 45.]])

In [24]:
from scipy import linalg

In [31]:
#  3x + 2y = 12
#  2x - y  = 1

A = np.array([[3,2],[2,-1]])
A

array([[ 3,  2],
       [ 2, -1]])

In [29]:
b = np.array([12,1])
b.shape

(2,)

In [32]:
A, b

(array([[ 3,  2],
        [ 2, -1]]),
 array([12,  1]))

In [33]:
x = linalg.solve(A,b)
x

array([2., 3.])

In [41]:
# Ax = b
# x = inv(A)*b
another_sol = linalg.inv(A) @ b
another_sol

array([2., 3.])

In [35]:
import sympy as smp

In [36]:
x, y  = smp.symbols('x y')

In [38]:
a = smp.cos(x)
a

cos(x)

In [39]:
smp.diff(a)

-sin(x)

In [43]:
c = x**2 + y**2
smp.diff(c, x)

2*x

In [45]:
f, g = smp.symbols('f g', cls=smp.Function)

In [46]:
f = f(x)

In [47]:
g = g(x)

In [48]:
smp.diff(f + g, x)

Derivative(f(x), x) + Derivative(g(x), x)

In [49]:
smp.diff(f*g, x)

f(x)*Derivative(g(x), x) + g(x)*Derivative(f(x), x)

In [50]:
f = x + 2*y

In [51]:
f.subs(x,12)

2*y + 12

In [52]:
n = smp.symbols('n')

In [53]:
s = smp.atan(n)/n**smp.Rational(11/10)

In [54]:
s

atan(n)/n**(2476979795053773/2251799813685248)

In [56]:
thesum = smp.Sum(s, (n,1,smp.oo))
thesum

Sum(atan(n)/n**(2476979795053773/2251799813685248), (n, 1, oo))

In [57]:
thesum.doit()

Sum(atan(n)/n**(2476979795053773/2251799813685248), (n, 1, oo))

In [58]:
thesum.n()

KeyboardInterrupt: 

In [59]:
k = smp.symbols('k')
k = x**2

In [61]:
smp.integrate(k,x)

x**3/3

In [63]:
A = np.array([[1,2],[3,4],[5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
U, Sigma, VT = linalg.svd(A, full_matrices=False)
print(U)
print(Sigma)
reA = U.dot(np.diag(Sigma)).dot(VT)
reA

[[-0.2298477   0.88346102]
 [-0.52474482  0.24078249]
 [-0.81964194 -0.40189603]]
[9.52551809 0.51430058]


array([[1., 2.],
       [3., 4.],
       [5., 6.]])